"""Seed bank of short motivational lines for the dashboard greeting slot.

All lines are original (no third-party copyrights). Displayed one random
line per dashboard visit via GET /quotes/random.
"""

QUOTES = [
    "Small steps every day grow into forests.",
    "Discipline beats motivation when the exam is near.",
    "Read one more page than yesterday.",
    "Every expert was once a beginner with a book.",
    "Consistency is the quietest superpower.",
    "Plant effort today, shade tomorrow.",
    "The syllabus shrinks when you show up daily.",
    "Mistakes reviewed are marks earned.",
    "Slow progress is still progress.",
    "Your future self is watching this session.",
    "Ten focused minutes beat an hour of scrolling.",
    "Roots grow in the dark; keep studying.",
    "Revise thrice, forget never.",
    "The exam rewards the prepared, not the lucky.",
    "One MCQ at a time, one mark at a time.",
    "Toppers are made in ordinary study hours.",
    "Doubt kills more dreams than failure.",
    "A calm mind answers better than a rushed one.",
    "Learn the concept, the options take care of themselves.",
    "Yesterday's wrong answer is today's easy mark.",
    "Study like the result depends on it. It does.",
    "Short sessions, done daily, move mountains.",
    "The forest of knowledge grows one tree at a time.",
    "Skip excuses, not revisions.",
    "Your competition is yesterday's you.",
    "Read, recall, repeat: that is the whole secret.",
    "Confidence comes from solved papers.",
    "Difficult chapters hide the most marks.",
    "Start before you feel ready.",
    "A notebook full of mistakes is a goldmine.",
    "Great oaks from little acorns grow.",
    "The best time to revise was yesterday; the next best is now.",
    "Focus is a muscle. Train it daily.",
    "Every mock you attempt makes the hall less scary.",
    "Winners review what losers skip.",
    "Knowledge compounds like interest.",
    "Stay curious; curiosity remembers longer.",
    "The-мини syllabus you fear most deserves mornings.",
    "Write it once, remember it twice.",
    "A steady lamp outlasts a bright flash.",
    "Exams test patience as much as memory.",
    "Turn weak chapters into strong comebacks.",
    "The one who persists, qualifies.",
    "Read actively. Question every line.",
    "Your pen remembers what your eyes forget.",
    "Five more questions. Then five more.",
    "Preparation turns pressure into performance.",
    "The mountain is climbed one step at a time.",
    "Do the hard chapter first; the day gets easier.",
    "Memory loves repetition and sleep.",
    "Test yourself before the examiner does.",
    "Small daily wins build unbeatable momentum.",
    "A goal without practice is just a wish.",
    "Study smart: high-weight topics first.",
    "The answer you earn yourself, you keep.",
    "Boring consistency creates exciting results.",
    "Ask why, not just what.",
    "Every revision doubles your retention.",
    "Fear fades with familiarity. Practice more.",
    "The paper respects preparation.",
    "Learn from every wrong tick.",
    "Today's effort is tomorrow's rank.",
    "Keep going; the breakthrough is near.",
    "A prepared mind sees patterns others miss.",
    "Divide the syllabus, conquer it daily.",
    "Your rank is built in these quiet hours.",
    "Read the question twice, answer once.",
    "Eliminate wrong options like clearing a trail.",
    "Time management is a practiced skill.",
    "The early riser revises twice.",
    "Notes in your own words stick longest.",
    "Trust your preparation on exam day.",
    "Every topper once stared at page one.",
    "Study with intent, not just hours.",
    "The seeds of success need daily water.",
    "Confusion today, clarity tomorrow. Keep going.",
    "Master the basics; the rest follows.",
    "A short break sharpens a long session.",
    "Compare, contrast, connect. Then remember.",
    "Your effort today writes your result.",
    "No shortcut beats spaced repetition.",
    "The forest rewards those who walk it daily.",
    "Answer with reason, not with hurry.",
    "Previous papers are prophecy. Solve them.",
    "Calm breathing, clear answering.",
    "One concept mastered beats ten skimmed.",
    "Let your preparation speak in the hall.",
    "Growth hides inside discomfort.",
    "Revise the forgotten before learning the new.",
    "A question practiced is a mark protected.",
    "Stay humble, stay hungry, stay consistent.",
    "The syllabus ends where your effort begins.",
    "Dream big, revise bigger.",
    "Patience in preparation, speed in the paper.",
    "What gets revised gets retained.",
    "Your dedication is your admit card.",
    "Learn a little about a lot, a lot about a little.",
    "The best revision is active recall.",
    "Keep your streak alive: one quiz a day.",
    "Doubt your doubts, trust your training.",
    "Marks follow mastery.",
    "Finish what you start. Every session counts.",
    "A focused hour outweighs a distracted day.",
    "The exam hall favors the well-rehearsed.",
    "Study today so tomorrow thanks you.",
    "Persistence turns average into excellent.",
    "Read less, recall more.",
    "Your only limit is yesterday's effort.",
    "Conquer one topic before sunrise.",
    "Smart work plus hard work wins ranks.",
]
